apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "lightspin-kubecollector.worker.fullname" . }}
  labels:
    {{- include "lightspin-kubecollector.worker.labels" . | nindent 4 }}
{{ include "lightspin-kubecollector.namespace" . | indent 2 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "lightspin-kubecollector.worker.matchLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lightspin-kubecollector.worker.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "lightspin-kubecollector.worker.serviceAccountName" . }}
      automountServiceAccountToken: true
      {{- with .Values.worker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name:  {{ .Values.worker.name }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command: ['celery', '-A', 'celeryapp', 'worker', '-l', 'INFO', '-c', {{ .Values.worker.config.concurrency | squote }}, '-P', 'gevent']
          envFrom:
            - configMapRef:
                name: light-kubecollector-cm
            - secretRef:
                name: {{ template "lightspin-kubecollector.apikey" . }}
          resources:
            {{- toYaml .Values.broker.resources | nindent 12 }}
      {{- with .Values.broker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.broker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.broker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

