apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "lightspin-kubecollector.name" . }}-redis-access
{{ include "lightspin-kubecollector.namespace" . | indent 2 }}
spec:
  podSelector:
    matchLabels:
      {{- include "lightspin-kubecollector.broker.matchLabels" . | nindent 6 }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "lightspin-kubecollector.beat.matchLabels" . | nindent 10 }}
    - podSelector:
        matchLabels:
          {{- include "lightspin-kubecollector.worker.matchLabels" . | nindent 10 }}
    ports:
      - port: {{ .Values.broker.config.port }}