apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "lightspin-kubecollector.worker.fullname" . }}-internet-egress
{{ include "lightspin-kubecollector.namespace" . | indent 2 }}
spec:
  podSelector:
    matchLabels:
      {{- include "lightspin-kubecollector.broker.matchLabels" . | nindent 6 }}
  egress:
  - {}
  policyTypes:
  - Egress

