{{- if .Values.runtime.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: light-kuberuntime-events-access
{{ include "lightspin-kubecollector.namespace" . | indent 2 }}
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: lightspin-runtime
    ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      {{- include "lightspin-kubecollector.runtime.events.matchLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
{{- end -}}