{{- if .Values.runtime.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: light-kuberuntime-events-internet-egress
{{ include "lightspin-kubecollector.namespace" . | indent 2 }}
spec:
  podSelector:
    matchLabels:
      {{- include "lightspin-kubecollector.runtime.events.matchLabels" . | nindent 6 }}
  egress:
  - {}
  policyTypes:
  - Egress
{{- end -}}