{{- if .Values.runtime.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "lightspin-kubecollector.runtime.falco.labels" . | nindent 4 }}
  name: {{ template "lightspin-kubecollector.runtime.falco.serviceAccountName" . }}
{{ include "lightspin-kubecollector.namespace" . | indent 2 }}
{{- end -}}