{{- if .Values.runtime.enabled -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "lightspin-kubecollector.runtime.falco.fullname" . }}
  labels:
    {{- include "lightspin-kubecollector.runtime.falco.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "lightspin-kubecollector.runtime.falco.serviceAccountName" . }}
{{ include "lightspin-kubecollector.namespace" . | indent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ template "lightspin-kubecollector.runtime.falco.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}