kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lightspin-secaudit
rules:
  - apiGroups: ["*"]
    resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations", "customresourcedefinitions", "apiservices", "controllerrevisions", "daemonsets", "deployments", "replicasets", "statefulsets", "horizontalpodautoscalers", "cronjobs", "jobs", "certificatesigningrequests", "leases", "endpointslices", "events", "flowschemas", "prioritylevelconfigurations", "nodes", "pods", "storagestates", "storageversionmigrations", "ingressclasses", "ingresses", "networkpolicies", "runtimeclasses", "poddisruptionbudgets", "podsecuritypolicies", "clusterrolebindings", "clusterroles", "rolebindings", "roles", "priorityclasses", "volumesnapshotclasses", "volumesnapshotcontents", "volumesnapshots", "csidrivers", "csinodes", "storageclasses", "volumeattachments", "csistoragecapacities", "componentstatuses", "configmaps", "endpoints", "events", "limitranges", "namespaces", "nodes", "persistentvolumeclaims", "persistentvolumes", "pods", "podtemplates", "replicationcontrollers", "resourcequotas", "serviceaccounts", "services"]
    verbs: ["get", "list"]
  - apiGroups: ["*"]
    resources: ["secrets"]
    verbs: ["get"]