apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "lightspin-kubecollector.worker.fullname" . }}
  labels:
    {{- include "lightspin-kubecollector.worker.labels" . | nindent 4 }}
{{ include "lightspin-kubecollector.namespace" . | indent 2 }}
roleRef:
  kind: Role
  name: {{ template "lightspin-kubecollector.worker.fullname" . }}
  apiGroup: ""
subjects:
- kind: ServiceAccount
  name: {{ template "lightspin-kubecollector.worker.serviceAccountName" . }}

