apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "lightspin-kubecollector.worker.labels" . | nindent 4 }}
  name: {{ template "lightspin-kubecollector.worker.serviceAccountName" . }}
{{ include "lightspin-kubecollector.namespace" . | indent 2 }}