{{- if not .Values.apiKeyExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: api-key
{{ include "lightspin-kubecollector.namespace" . | indent 2 }}
type: Opaque
data:
  API_KEY: {{  default "MISSING-VARIABLE" .Values.apiKey | b64enc | quote }}
{{- end }}