apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "lightspin-kubecollector.broker.labels" . | nindent 4 }}
  name: redis-config
{{ include "lightspin-kubecollector.namespace" . | indent 2 }}

data:
  redis-config: 'bind 0.0.0.0'