{{- if .Values.runtime.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: light-kuberuntime-events-svc
{{ include "lightspin-kubecollector.namespace" . | indent 2 }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "lightspin-kubecollector.runtime.events.matchLabels" . | nindent 6 }}
{{- end -}}